"""empty message

Revision ID: 522c9918cfff
Revises: 
Create Date: 2022-12-08 16:44:59.713387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522c9918cfff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('additional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polish', sa.Boolean(), nullable=True),
    sa.Column('cabinets', sa.Boolean(), nullable=True),
    sa.Column('baseBoards', sa.Boolean(), nullable=True),
    sa.Column('fridge', sa.Boolean(), nullable=True),
    sa.Column('windows', sa.Boolean(), nullable=True),
    sa.Column('skylights', sa.Boolean(), nullable=True),
    sa.Column('carpetShampoo', sa.Boolean(), nullable=True),
    sa.Column('quote', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('square_foot', sa.Integer(), nullable=False),
    sa.Column('requested_service', sa.String(), nullable=False),
    sa.Column('quote', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('additional')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
