"""empty message

Revision ID: ae9f2eefaaeb
Revises: edb869667256
Create Date: 2022-12-07 19:22:15.171984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9f2eefaaeb'
down_revision = 'edb869667256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('service_owner_fkey', 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'user', ['user_id'], ['id'])
    op.drop_column('service', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key('service_owner_fkey', 'service', 'user', ['owner'], ['id'])
    op.drop_column('service', 'user_id')
    # ### end Alembic commands ###
