"""empty message

Revision ID: edb869667256
Revises: f44f209d6df7
Create Date: 2022-12-07 19:15:28.623601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb869667256'
down_revision = 'f44f209d6df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    # ### end Alembic commands ###
